# Generated by Django 3.2.6 on 2023-10-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.TextField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
